# Generated by Django 4.0.1 on 2023-01-26 16:47

import core.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(blank=True, max_length=100, null=True)),
                ('icon_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('privacy_policy', models.CharField(blank=True, max_length=100000, null=True)),
                ('about_us', models.CharField(blank=True, max_length=10000, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=100, null=True)),
                ('agree_text', models.CharField(blank=True, max_length=100000, null=True)),
                ('payment_info_text', models.CharField(blank=True, max_length=100000, null=True)),
                ('payment_info_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('product_expire_days', models.IntegerField(blank=True, null=True)),
                ('products_num', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('approved', 'approved'), ('disabled', 'disabled')], max_length=100, null=True)),
                ('photo', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.date.today)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('contact', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, choices=[('approved', 'approved'), ('disabled', 'disabled')], default='approved', max_length=100, null=True)),
                ('fields', models.JSONField(default=core.models.default_category_fields, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('mainCategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 26, 19, 47, 10, 500035, tzinfo=utc), null=True)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('approved', 'approved'), ('declined', 'declined'), ('pending', 'pending'), ('sold', 'sold'), ('Deleted', 'Deleted')], max_length=100, null=True)),
                ('photos', models.JSONField(default=core.models.default_fields, null=True)),
                ('fields', models.JSONField(default=core.models.default_fields, null=True)),
                ('uudi', models.CharField(blank=True, max_length=100, null=True)),
                ('views', models.IntegerField(blank=True, default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('subCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.subcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=1000)),
                ('date', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentReplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('replaies', models.ManyToManyField(to='core.CommentReplay')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
