# Generated by Django 4.0.1 on 2022-12-02 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ADS',
            new_name='AD',
        ),
    ]
