# Generated by Django 4.1.4 on 2022-12-22 17:07

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='fields',
            field=models.JSONField(default=core.models.get_default, null=True),
        ),
    ]
