# Generated by Django 4.0.1 on 2023-01-26 17:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='auto_approve',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 26, 20, 26, 43, 510501, tzinfo=utc), null=True),
        ),
    ]
