# Generated by Django 4.0.1 on 2023-01-26 17:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_about_auto_approve_alter_product_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='auto_approve',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 26, 20, 32, 39, 560766, tzinfo=utc), null=True),
        ),
    ]
