# Generated by Django 4.0.1 on 2023-01-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_commentreplay_comment_replaies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='replaies',
            field=models.ManyToManyField(to='core.CommentReplay'),
        ),
    ]
