# Generated by Django 4.0.1 on 2023-01-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='products_num',
            field=models.IntegerField(default=0),
        ),
    ]
