# Generated by Django 4.0.1 on 2022-12-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='contact',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
