# Generated by Django 4.0.1 on 2022-12-10 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ad_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('A', 'approved'), ('D', 'declined'), ('P', 'pending'), ('S', 'sold'), ('D', 'Deleted')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('photo', models.CharField(blank=True, max_length=1000, null=True)),
                ('mainCategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.subcategory'),
        ),
    ]
