# Generated by Django 4.0.1 on 2022-12-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_ad_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(blank=True, choices=[('approved', 'approved'), ('disabled', 'disabled')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('approved', 'approved'), ('declined', 'declined'), ('pending', 'pending'), ('sold', 'sold'), ('Deleted', 'Deleted')], max_length=100, null=True),
        ),
    ]
