# Generated by Django 4.0.1 on 2022-12-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_category_status_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(blank=True, choices=[('approved', 'approved'), ('disabled', 'disabled')], default='approved', max_length=100, null=True),
        ),
    ]
