# Generated by Django 4.0.1 on 2023-01-22 10:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_about_about_us_alter_about_agree_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 22, 13, 36, 13, 821963, tzinfo=utc), null=True),
        ),
    ]
