# Generated by Django 4.0.1 on 2022-12-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_category_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
