# Generated by Django 4.0.1 on 2022-12-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_ad_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.CharField(blank=True, choices=[('approved', 'approved'), ('disabled', 'disabled')], default='approved', max_length=100),
        ),
    ]
