# Generated by Django 4.0.1 on 2022-12-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_ad_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.CharField(blank=True, choices=[('approved', 'approved'), ('disabled', 'disabled')], max_length=100, null=True),
        ),
    ]
