# Generated by Django 4.0.1 on 2022-12-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_category_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='fields',
            field=models.JSONField(default={'price': 'required', 'title': 'required'}, null=True),
        ),
    ]
