# Generated by Django 4.0.1 on 2022-12-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_product_date_alter_product_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
