# Generated by Django 4.0.1 on 2022-12-18 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_product_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='expire_date',
        ),
    ]
