# Generated by Django 4.0.1 on 2022-12-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_product_date_remove_product_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
