# Generated by Django 4.0.1 on 2022-12-18 18:03

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_product_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='fields',
            field=models.JSONField(default=core.models.get_default, null=True),
        ),
    ]
