# Generated by Django 4.0.1 on 2022-12-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_product_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_policy', models.CharField(max_length=100000, null=True)),
                ('about_us', models.CharField(max_length=10000, null=True)),
                ('contact_number', models.CharField(max_length=100, null=True)),
                ('whatsup_number', models.CharField(max_length=100, null=True)),
                ('agree_text', models.CharField(max_length=100000, null=True)),
            ],
        ),
    ]
