# Generated by Django 4.0.1 on 2022-12-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='payment_info_text',
            field=models.CharField(max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='paymney_info_link',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
