# Generated by Django 4.0.1 on 2022-12-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_about_payment_info_text_about_paymney_info_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='paymney_info_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
