# Generated by Django 4.0.1 on 2022-12-19 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_about_paymney_info_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='paymney_info_link',
            new_name='paymnet_info_link',
        ),
    ]
