# Generated by Django 4.0.1 on 2022-12-19 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_rename_paymney_info_link_about_paymnet_info_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='paymnet_info_link',
            new_name='payment_info_link',
        ),
    ]
