# Generated by Django 4.0.1 on 2022-12-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_rename_paymnet_info_link_about_payment_info_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='app_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='icon_link',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
